Github:
- .github/**/*

Images:
- static/images/**/*

Architecture:
- local/**/*
- layouts/**/*
- config/**/*
- assets/styles/**/*
- assets/scripts/**/*

$1:
- content/en/([^/]+)/.*

FAQ:
- content/en/*/faq/*

Guide:
- content/en/*/guide/*
